### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by silliershark** [ItsMax123/AntiGlitch#15]
Adding anti noclip glitch when you want to force enter the block in the anti-break area

**Comment by ItsMax123** [comment]
Do you mean when people break blocks to get through them?

**Comment by silliershark** [comment]
No i mean anti clip cant inside to block

**Comment by silliershark** [comment]
No i mean anti clip cant inside to block

**Comment by silliershark** [comment]
Anti clip hack

**Comment by ItsMax123** [comment]
If its a hack then you might want to look for an anti-cheat and not an anti-glitch…

**Comment by silliershark** [comment]
Is same glitch too but u cant inside the block
