### ISSUE TITLE
[Bug] Falling out of the world with Enderpearl

### ISSUE THREAD

**Issue by MrBlasyMSK** [ItsMax123/AntiGlitch#16]
**Steps to reproduce the bug**
Throw an enderpearl at the wall and just fall to avoid

**Error report**
No error

**Plugin version, Pocketmine version**
Are you using the latest version of the plugin? Y
Are you using the latest version of pocketmine? Y

**Plugins used**
I have this option disabled

Video:
https://streamable.com/3e8ikl

**Comment by ItsMax123** [comment]
Fixed in latest update
