### ISSUE TITLE
[Bug] AntiDoor is complete garbage

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [ItsMax123/AntiGlitch#19]
**Steps to reproduce the bug**
Step 1: Place door
Step 2: Get out of op
Step 3: Spam and run
Step 4: STONKS

**Error report**
No error

**Plugin version, Pocketmine version**
Are you using the latest version of the plugin? 
Yes
Are you using the latest version of pocketmine? Yes (pm3)

**Plugins used**
No

**Comment by ZZWILLIAMXXTrue** [comment]
https://user-images.githubusercontent.com/49970753/142750057-4a6e1feb-b6b5-40bf-a415-3b711cc58f0c.MOV

**Comment by ZZWILLIAMXXTrue** [comment]
Hey I sent you a friend request on discord because I want to make the anti epearl glitch 100% work, so far I have found one way to glitch through walls

**Comment by ItsMax123** [comment]
Are you sure you turned the antidoor to true in config?

**Comment by ZZWILLIAMXXTrue** [comment]
Yes
